"""Mensajes relacionados con el flujo de registro de proveedores."""

from .confirmacion import (
    CONFIRM_ACCEPT_ID,
    CONFIRM_REJECT_ID,
    payload_confirmacion_resumen,
)
from .resumen_consentimiento import (
    construir_resumen_consentimiento_registro,
    payload_resumen_consentimiento_registro,
)
from .confirmacion_servicios import (
    mensaje_confirmacion_servicios,
    mensaje_correccion_servicios,
    mensaje_lista_servicios_corregida,
    mensaje_servicios_aceptados,
)
from .perfil_profesional import (
    CERTIFICATE_SKIP_ID,
    construir_resumen_confirmacion_perfil_profesional,
    mensaje_menu_edicion_perfil_profesional,
    PROFILE_CONTROL_IDS,
    PROFILE_SINGLE_USE_CONTROL_IDS,
    SERVICE_ADD_NO_ID,
    SERVICE_ADD_YES_ID,
    SERVICE_CONFIRM_ID,
    SERVICE_CORRECT_ID,
    SOCIAL_FACEBOOK_ID,
    SOCIAL_INSTAGRAM_ID,
    SOCIAL_SKIP_ID,
    mensaje_error_certificado_invalido,
    mensaje_inicio_perfil_profesional,
    mensaje_minimo_servicios_pendiente,
    payload_agregar_otro_servicio,
    payload_confirmacion_servicio_perfil,
    payload_certificado_opcional,
    payload_red_social_opcional,
    payload_red_social_opcional_estado,
    preguntar_experiencia_general,
    preguntar_nombre,
)
from templates.onboarding.caducidad import (
    TEMPLATE_EXPIRY_72H_ID,
    TEMPLATE_EXPIRY_72H_LANGUAGE,
    TEMPLATE_WARNING_48H_ID,
    TEMPLATE_WARNING_48H_LANGUAGE,
    payload_baja_onboarding_72h,
    payload_recordatorio_onboarding_48h,
)
from .servicios import (
    confirmar_servicio_y_preguntar_otro,
    mensaje_debes_registrar_al_menos_un_servicio,
    mensaje_debes_registrar_mas_servicios,
    mensaje_error_opcion_agregar_otro,
    mensaje_error_opcion_edicion_servicios,
    mensaje_maximo_servicios_registro,
    mensaje_menu_edicion_servicios_registro,
    mensaje_resumen_servicios_registro,
    mensaje_servicio_actualizado,
    mensaje_servicio_duplicado_registro,
    mensaje_servicio_eliminado_registro,
    payload_resumen_servicios_registro,
    preguntar_nuevo_servicio_reemplazo,
    preguntar_numero_servicio_eliminar,
    preguntar_numero_servicio_reemplazar,
    preguntar_siguiente_servicio_registro,
)
from templates.onboarding.telefono import (
    error_real_phone_invalido,
    preguntar_real_phone,
)
__all__ = [
    # Pasos de registro
    "preguntar_real_phone",
    "error_real_phone_invalido",
    "mensaje_inicio_perfil_profesional",
    "preguntar_experiencia_general",
    # Confirmación
    "payload_confirmacion_resumen",
    "construir_resumen_consentimiento_registro",
    "payload_resumen_consentimiento_registro",
    "CONFIRM_ACCEPT_ID",
    "CONFIRM_REJECT_ID",
    # Confirmación de servicios
    "mensaje_confirmacion_servicios",
    "mensaje_correccion_servicios",
    "mensaje_servicios_aceptados",
    "mensaje_lista_servicios_corregida",
    "preguntar_siguiente_servicio_registro",
    "confirmar_servicio_y_preguntar_otro",
    "payload_agregar_otro_servicio",
    "payload_confirmacion_servicio_perfil",
    "mensaje_resumen_servicios_registro",
    "mensaje_menu_edicion_servicios_registro",
    "preguntar_numero_servicio_reemplazar",
    "preguntar_numero_servicio_eliminar",
    "preguntar_nuevo_servicio_reemplazo",
    "mensaje_servicio_actualizado",
    "mensaje_servicio_eliminado_registro",
    "mensaje_servicio_duplicado_registro",
    "mensaje_maximo_servicios_registro",
    "payload_resumen_servicios_registro",
    "mensaje_debes_registrar_al_menos_un_servicio",
    "mensaje_debes_registrar_mas_servicios",
    "mensaje_error_opcion_agregar_otro",
    "mensaje_error_opcion_edicion_servicios",
    "payload_red_social_opcional",
    "payload_red_social_opcional_estado",
    "payload_certificado_opcional",
    "mensaje_error_certificado_invalido",
    "mensaje_minimo_servicios_pendiente",
    "construir_resumen_confirmacion_perfil_profesional",
    "preguntar_nombre",
    "mensaje_menu_edicion_perfil_profesional",
    "payload_recordatorio_onboarding_48h",
    "payload_baja_onboarding_72h",
    "TEMPLATE_WARNING_48H_ID",
    "TEMPLATE_WARNING_48H_LANGUAGE",
    "TEMPLATE_EXPIRY_72H_ID",
    "TEMPLATE_EXPIRY_72H_LANGUAGE",
    "PROFILE_CONTROL_IDS",
    "PROFILE_SINGLE_USE_CONTROL_IDS",
    "SOCIAL_SKIP_ID",
    "SOCIAL_FACEBOOK_ID",
    "SOCIAL_INSTAGRAM_ID",
    "CERTIFICATE_SKIP_ID",
    "SERVICE_ADD_YES_ID",
    "SERVICE_ADD_NO_ID",
    "SERVICE_CONFIRM_ID",
    "SERVICE_CORRECT_ID",
]
