"""Mensajes y payloads del onboarding de proveedores."""

from .inicio import (
    MENU_REGISTRO_HEADER_IMAGE_URL_ENV,
    MENU_REGISTRO_PROVEEDOR,
    ONBOARDING_REGISTER_BUTTON_ID,
    payload_menu_registro_proveedor,
)
from .ciudad import (
    ERROR_CIUDAD_CARACTERES_INVALIDOS,
    ERROR_CIUDAD_CORTA,
    ERROR_CIUDAD_FRASE,
    ERROR_CIUDAD_LARGA,
    ERROR_CIUDAD_MULTIPLE,
    ERROR_CIUDAD_NO_RECONOCIDA,
    ONBOARDING_CITY_LOCATION_REQUEST_INITIAL_ID,
    ONBOARDING_CITY_LOCATION_REQUEST_UPDATE_ID,
    error_ciudad_caracteres_invalidos,
    error_ciudad_corta,
    error_ciudad_frase,
    error_ciudad_larga,
    error_ciudad_multiple,
    error_ciudad_no_reconocida,
    mensaje_error_resolviendo_ubicacion,
    preguntar_actualizar_ciudad,
    preguntar_ciudad,
    solicitar_ciudad_actualizacion,
    solicitar_ciudad_registro,
    ui_solicitud_ubicacion,
)
from .documentos import (
    DNI_FRONT_GUIDE_URL_ENV,
    PROFILE_PHOTO_GUIDE_URL_ENV,
    payload_onboarding_dni_frontal,
    payload_onboarding_foto_perfil,
    solicitar_onboarding_dni_frontal,
    solicitar_onboarding_foto_perfil,
)
from .experiencia import (
    ONBOARDING_EXPERIENCE_10_PLUS_ID,
    ONBOARDING_EXPERIENCE_1_3_ID,
    ONBOARDING_EXPERIENCE_3_5_ID,
    ONBOARDING_EXPERIENCE_5_10_ID,
    ONBOARDING_EXPERIENCE_RANGES_ID,
    ONBOARDING_EXPERIENCE_UNDER_1_ID,
    payload_experiencia_onboarding,
    preguntar_experiencia_onboarding,
)
from .servicios import (
    SERVICIOS_ONBOARDING_HEADER_IMAGE_URL_ENV,
    SERVICIOS_ONBOARDING_MAXIMOS,
    payload_servicios_onboarding_con_imagen,
    preguntar_servicios_onboarding,
)
from .redes_sociales import (
    REDES_SOCIALES_ONBOARDING_IMAGE_URL_ENV,
    REDES_SOCIALES_SKIP_ID,
    payload_redes_sociales_onboarding_con_imagen,
    preguntar_redes_sociales_onboarding,
)
from .consentimiento import (
    mensaje_consentimiento_rechazado,
    payload_consentimiento_proveedor,
)
from .caducidad import (
    TEMPLATE_EXPIRY_72H_ID,
    TEMPLATE_EXPIRY_72H_LANGUAGE,
    TEMPLATE_WARNING_48H_ID,
    TEMPLATE_WARNING_48H_LANGUAGE,
    payload_baja_onboarding_72h,
    payload_recordatorio_onboarding_48h,
)
from .telefono import (
    error_real_phone_invalido,
    preguntar_real_phone,
)

__all__ = [
    "MENU_REGISTRO_HEADER_IMAGE_URL_ENV",
    "MENU_REGISTRO_PROVEEDOR",
    "ONBOARDING_REGISTER_BUTTON_ID",
    "payload_menu_registro_proveedor",
    "ERROR_CIUDAD_CORTA",
    "ERROR_CIUDAD_LARGA",
    "ERROR_CIUDAD_CARACTERES_INVALIDOS",
    "ERROR_CIUDAD_MULTIPLE",
    "ERROR_CIUDAD_FRASE",
    "ERROR_CIUDAD_NO_RECONOCIDA",
    "ONBOARDING_CITY_LOCATION_REQUEST_INITIAL_ID",
    "ONBOARDING_CITY_LOCATION_REQUEST_UPDATE_ID",
    "error_ciudad_corta",
    "error_ciudad_larga",
    "error_ciudad_caracteres_invalidos",
    "error_ciudad_multiple",
    "error_ciudad_frase",
    "error_ciudad_no_reconocida",
    "mensaje_error_resolviendo_ubicacion",
    "preguntar_actualizar_ciudad",
    "preguntar_ciudad",
    "solicitar_ciudad_actualizacion",
    "solicitar_ciudad_registro",
    "ui_solicitud_ubicacion",
    "DNI_FRONT_GUIDE_URL_ENV",
    "PROFILE_PHOTO_GUIDE_URL_ENV",
    "payload_onboarding_dni_frontal",
    "payload_onboarding_foto_perfil",
    "solicitar_onboarding_dni_frontal",
    "solicitar_onboarding_foto_perfil",
    "ONBOARDING_EXPERIENCE_RANGES_ID",
    "ONBOARDING_EXPERIENCE_UNDER_1_ID",
    "ONBOARDING_EXPERIENCE_1_3_ID",
    "ONBOARDING_EXPERIENCE_3_5_ID",
    "ONBOARDING_EXPERIENCE_5_10_ID",
    "ONBOARDING_EXPERIENCE_10_PLUS_ID",
    "payload_experiencia_onboarding",
    "preguntar_experiencia_onboarding",
    "SERVICIOS_ONBOARDING_HEADER_IMAGE_URL_ENV",
    "SERVICIOS_ONBOARDING_MAXIMOS",
    "payload_servicios_onboarding_con_imagen",
    "preguntar_servicios_onboarding",
    "REDES_SOCIALES_ONBOARDING_IMAGE_URL_ENV",
    "REDES_SOCIALES_SKIP_ID",
    "payload_redes_sociales_onboarding_con_imagen",
    "preguntar_redes_sociales_onboarding",
    "payload_consentimiento_proveedor",
    "mensaje_consentimiento_rechazado",
    "payload_recordatorio_onboarding_48h",
    "payload_baja_onboarding_72h",
    "TEMPLATE_WARNING_48H_ID",
    "TEMPLATE_WARNING_48H_LANGUAGE",
    "TEMPLATE_EXPIRY_72H_ID",
    "TEMPLATE_EXPIRY_72H_LANGUAGE",
    "preguntar_real_phone",
    "error_real_phone_invalido",
]
