"""Mensajes y payloads del contexto maintenance."""

from .actualizacion_perfil import (
    confirmar_actualizacion_redes_sociales,
    confirmar_documentos_actualizados,
    confirmar_selfie_actualizada,
    error_actualizar_documentos,
    error_actualizar_redes_sociales,
    error_actualizar_selfie,
    solicitar_dni_actualizacion,
    solicitar_dni_frontal_actualizacion,
    solicitar_dni_reverso_actualizacion,
    solicitar_red_social_actualizacion,
    solicitar_selfie_actualizacion,
    solicitar_selfie_requerida,
)
from .confirmacion import (
    CONFIRM_ACCEPT_ID,
    CONFIRM_REJECT_ID,
    mensaje_resumen_confirmacion_registro,
    payload_confirmacion_resumen,
)
from .confirmacion_servicios import (
    mensaje_confirmacion_servicios,
    mensaje_correccion_servicios,
    mensaje_lista_servicios_corregida,
    mensaje_servicios_aceptados,
)
from .resumen import construir_resumen_confirmacion_registro
from .eliminacion_registro import (
    advertencia_eliminacion_irreversible,
    confirmar_eliminacion_exitosa,
    error_eliminacion_fallida,
    informar_eliminacion_cancelada,
    solicitar_confirmacion_eliminacion,
)
from .mensajes_servicios import (
    confirmar_servicio_eliminado,
    confirmar_servicios_agregados,
    error_eliminar_servicio,
    error_guardar_servicio,
    error_limite_servicios_alcanzado,
    error_servicio_no_interpretado,
    informar_limite_servicios_alcanzado,
    informar_sin_servicios_eliminar,
    mensaje_confirmacion_servicios_menu,
    mensaje_confirmar_o_corregir_servicio,
    mensaje_correccion_servicios_menu,
    mensaje_ejemplo_servicio_seleccionado,
    mensaje_limite_servicios_temporales,
    mensaje_numero_valido_eliminar_servicio,
    mensaje_numero_valido_reemplazo_servicio,
    payload_confirmacion_servicios_menu,
    preguntar_nuevo_servicio,
    preguntar_nuevo_servicio_con_ejemplos,
    preguntar_nuevo_servicio_con_ejemplos_dinamicos,
    preguntar_servicio_eliminar,
)

__all__ = [
    "solicitar_selfie_actualizacion",
    "solicitar_selfie_requerida",
    "confirmar_selfie_actualizada",
    "error_actualizar_selfie",
    "payload_confirmacion_resumen",
    "mensaje_resumen_confirmacion_registro",
    "CONFIRM_ACCEPT_ID",
    "CONFIRM_REJECT_ID",
    "mensaje_confirmacion_servicios",
    "mensaje_correccion_servicios",
    "mensaje_servicios_aceptados",
    "mensaje_lista_servicios_corregida",
    "construir_resumen_confirmacion_registro",
    "solicitar_red_social_actualizacion",
    "error_actualizar_redes_sociales",
    "confirmar_actualizacion_redes_sociales",
    "solicitar_dni_actualizacion",
    "solicitar_dni_frontal_actualizacion",
    "solicitar_dni_reverso_actualizacion",
    "confirmar_documentos_actualizados",
    "error_actualizar_documentos",
    "solicitar_confirmacion_eliminacion",
    "confirmar_eliminacion_exitosa",
    "error_eliminacion_fallida",
    "informar_eliminacion_cancelada",
    "advertencia_eliminacion_irreversible",
    "error_limite_servicios_alcanzado",
    "preguntar_nuevo_servicio",
    "preguntar_nuevo_servicio_con_ejemplos",
    "preguntar_nuevo_servicio_con_ejemplos_dinamicos",
    "mensaje_ejemplo_servicio_seleccionado",
    "error_servicio_no_interpretado",
    "error_guardar_servicio",
    "mensaje_confirmacion_servicios_menu",
    "mensaje_correccion_servicios_menu",
    "mensaje_confirmar_o_corregir_servicio",
    "payload_confirmacion_servicios_menu",
    "mensaje_numero_valido_reemplazo_servicio",
    "mensaje_numero_valido_eliminar_servicio",
    "mensaje_limite_servicios_temporales",
    "confirmar_servicios_agregados",
    "informar_limite_servicios_alcanzado",
    "informar_sin_servicios_eliminar",
    "preguntar_servicio_eliminar",
    "error_eliminar_servicio",
    "confirmar_servicio_eliminado",
]
