-- ================================================================
-- Script: Crear tabla y poblar catálogo de profesiones (sin duplicados)
-- Fuente: docs/listado_profesiones.md
-- ================================================================

-- Extensión para eliminar tildes (requiere PostgreSQL)
CREATE EXTENSION IF NOT EXISTS unaccent;

-- Crear tabla con campo de nombre normalizado
CREATE TABLE IF NOT EXISTS catalogue_profesiones (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    nombre_normalizado VARCHAR(150) NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'artesanal'
);

-- Índices
CREATE UNIQUE INDEX IF NOT EXISTS idx_catalogo_profesiones_nombre_normalizado
ON catalogue_profesiones(nombre_normalizado);

CREATE INDEX IF NOT EXISTS idx_catalogo_profesiones_tipo
ON catalogue_profesiones(tipo);

COMMENT ON TABLE catalogue_profesiones IS 'Catálogo de profesiones del sistema';
COMMENT ON COLUMN catalogue_profesiones.id IS 'Identificador único autoincremental';
COMMENT ON COLUMN catalogue_profesiones.nombre IS 'Nombre original de la profesión';
COMMENT ON COLUMN catalogue_profesiones.nombre_normalizado IS 'Nombre normalizado sin tildes, acentos ni preposiciones para búsquedas';
COMMENT ON COLUMN catalogue_profesiones.tipo IS 'Tipo de profesión (profesional, artesanal)';

-- ================================================================
-- INSERT: Profesionales
-- ================================================================

INSERT INTO catalogue_profesiones (nombre, nombre_normalizado, tipo) VALUES
('Licenciado en Ciencias de la Educación', 'ciencias de la educacion', 'profesional'),
('Licenciado en Ciencias de la Educación Inicial', 'ciencias de la educacion inicial', 'profesional'),
('Licenciado en Ciencias de la Educación Básica', 'ciencias de la educacion basica', 'profesional'),
('Licenciado en Ciencias de la Educación Especial', 'ciencias de la educacion especial', 'profesional'),
('Licenciado en Ciencias de la Educación Intercultural Bilingüe', 'ciencias de la educacion intercultural bilingue', 'profesional'),
('Licenciado en Pedagogía de las Matemáticas y la Física', 'pedagogia las matematicas la fisica', 'profesional'),
('Licenciado en Pedagogía de la Química y Biología', 'pedagogia la quimica biologia', 'profesional'),
('Licenciado en Pedagogía de la informática', 'pedagogia la informatica', 'profesional'),
('Licenciado en Pedagogía de la Historia y las Ciencias Sociales', 'pedagogia la historia las ciencias sociales', 'profesional'),
('Licenciado en Pedagogía de la Lengua y Literatura', 'pedagogia la lengua literatura', 'profesional'),
('Licenciado en Pedagogía de la Filosofía', 'pedagogia la filosofia', 'profesional'),
('Licenciado en Pedagogía de las Artes', 'pedagogia las artes', 'profesional'),
('Licenciado en Pedagogía del Idioma', 'pedagogia del idioma', 'profesional'),
('Licenciado en Pedagogía de la Actividad Física y Deporte', 'pedagogia la actividad fisica deporte', 'profesional'),
('Licenciado en Pedagogía Musical', 'pedagogia musical', 'profesional'),
('Licenciado en Educación en Ciencias Experimentales', 'educacion en ciencias experimentales', 'profesional'),
('Licenciado en Pedagogía Técnica de la Mecatrónica', 'pedagogia tecnica la mecatronica', 'profesional'),
('Licenciado en Psicopedagogía', 'psicopedagogia', 'profesional'),
('Licenciado en Técnicas Audiovisuales', 'tecnicas audiovisuales', 'profesional'),
('Licenciado en Animación Digital', 'animacion digital', 'profesional'),
('Licenciado en Producción para Medios de Comunicación', 'produccion para medios comunicacion', 'profesional'),
('Licenciado en Multimedia y Producción Audiovisual', 'multimedia produccion audiovisual', 'profesional'),
('Licenciado en Diseño Textil e Indumentaria', 'diseno textil indumentaria', 'profesional'),
('Licenciado en Diseño Gráfico', 'diseno grafico', 'profesional'),
('Licenciado en Diseño de Interiores', 'diseno interiores', 'profesional'),
('Licenciado en Diseño de Productos', 'diseno productos', 'profesional'),
('Licenciado en Artes Plásticas', 'artes plasticas', 'profesional'),
('Licenciado en Curaduría', 'curaduria', 'profesional'),
('Licenciado en Artes Visuales', 'artes visuales', 'profesional'),
('Licenciado en Artes Escénicas', 'artes escenicas', 'profesional'),
('Licenciado en Artes Musicales', 'artes musicales', 'profesional'),
('Licenciado en Artes Musicales y Sonoras', 'artes musicales sonoras', 'profesional'),
('Licenciado en Cine', 'cine', 'profesional'),
('Licenciado en Creación Teatral', 'creacion teatral', 'profesional'),
('Licenciado en Producción Musical y Sonora', 'produccion musical sonora', 'profesional'),
('Licenciado en Danza', 'danza', 'profesional'),
('Licenciado en Teología', 'teologia', 'profesional'),
('Licenciado en Pedagogía de la Religión', 'pedagogia religion', 'profesional'),
('Licenciado en Historia', 'historia', 'profesional'),
('Licenciado en Arqueología', 'arqueologia', 'profesional'),
('Licenciado en Crítica e Historia del Arte', 'critica historia del arte', 'profesional'),
('Licenciado en Filosofía', 'filosofia', 'profesional'),
('Licenciado en Idioma', 'idioma', 'profesional'),
('Licenciado en Literatura', 'literatura', 'profesional'),
('Licenciado en Lingüística', 'linguistica', 'profesional'),
('Economista', 'economista', 'profesional'),
('Licenciado en Ciencias Políticas', 'ciencias politicas', 'profesional'),
('Licenciado en Relaciones Internacionales', 'relaciones internacionales', 'profesional'),
('Licenciado en Desarrollo Local', 'desarrollo local', 'profesional'),
('Licenciado en Gestión Social y Desarrollo', 'gestion social desarrollo', 'profesional'),
('Licenciado en Psicología', 'psicologia', 'profesional'),
('Licenciado en Psicología Educativa', 'psicologia educativa', 'profesional'),
('Licenciado en Psicología Organizacional', 'psicologia organizacional', 'profesional'),
('Licenciado en Estudios Culturales', 'estudios culturales', 'profesional'),
('Licenciado en Sociología', 'sociologia', 'profesional'),
('Licenciado en Antropología', 'antropologia', 'profesional'),
('Licenciado en Trabajo Social', 'trabajo social', 'profesional'),
('Licenciado en Orientación Familiar', 'orientacion familiar', 'profesional'),
('Licenciado en Artes Liberales', 'artes liberales', 'profesional'),
('Licenciado en Estudios Internacionales', 'estudios internacionales', 'profesional'),
('Licenciado en Género y Desarrollo', 'genero desarrollo', 'profesional'),
('Licenciado en Geografía y Territorio', 'geografia territorio', 'profesional'),
('Licenciado en Economía Matemática', 'economia matematica', 'profesional'),
('Licenciado en Periodismo', 'periodismo', 'profesional'),
('Licenciado en Comunicación', 'comunicacion', 'profesional'),
('Licenciado en Publicidad', 'publicidad', 'profesional'),
('Licenciado en Bibliotecología Documentación y Archivo', 'bibliotecologia documentacion archivo', 'profesional'),
('Abogado', 'abogado', 'profesional'),
('Licenciado en Criminalística', 'criminalistica', 'profesional'),
('Licenciado en Contabilidad y Auditoría', 'contabilidad auditoria', 'profesional'),
('Licenciado en Auditoría y Control de Gestión', 'auditoria control gestion', 'profesional'),
('Licenciado en Finanzas', 'finanzas', 'profesional'),
('Licenciado en Administración Pública', 'administracion publica', 'profesional'),
('Licenciado en Administración de Empresas', 'administracion empresas', 'profesional'),
('Licenciado en Emprendimiento e Innovación Social', 'emprendimiento innovacion social', 'profesional'),
('Licenciado en Agronegocios', 'agronegocios', 'profesional'),
('Licenciado en Negocios Digitales', 'negocios digitales', 'profesional'),
('Licenciado en Mercadotecnia', 'mercadotecnia', 'profesional'),
('Licenciado en Marketing', 'marketing', 'profesional'),
('Licenciado en Marketing Digital', 'marketing digital', 'profesional'),
('Licenciado en Gestión de la Información Gerencial', 'gestion informacion gerencial', 'profesional'),
('Licenciado en Gerencia y Liderazgo', 'gerencia liderazgo', 'profesional'),
('Licenciado en Comercio', 'comercio', 'profesional'),
('Licenciado en Comercio Exterior', 'comercio exterior', 'profesional'),
('Licenciado en Biocomercio', 'biocomercio', 'profesional'),
('Licenciado en Gestión del Talento Humano', 'gestion talento humano', 'profesional'),
('Licenciado en Negocios Internacionales', 'negocios internacionales', 'profesional'),
('Licenciado en Gestión Tecnológica', 'gestion tecnologica', 'profesional'),
('Biólogo', 'bilogo', 'profesional'),
('Ingeniero Biotecnólogo', 'ingeniero biotecnologo', 'profesional'),
('Licenciado en Microbiología', 'microbiologia', 'profesional'),
('Bioquímico', 'bioquimico', 'profesional'),
('Licenciado en Biofísica', 'biofisica', 'profesional'),
('Licenciado en Biofarmacéutica', 'biofarmaceutica', 'profesional'),
('Ingeniero Biomédico', 'ingeniero biomedico', 'profesional'),
('Ingeniero Genético', 'ingeniero genetico', 'profesional'),
('Ingeniero en Biodiversidad y Recursos Genéticos', 'ingeniero biodiversidad recursos geneticos', 'profesional'),
('Licenciado en Neurociencias', 'neurociencias', 'profesional'),
('Licenciado en Ecología', 'ecologia', 'profesional'),
('Ingeniero en Ecosistemas', 'ingeniero ecosistemas', 'profesional'),
('Ingeniero en Recursos Naturales Renovables', 'ingeniero recursos naturales renovables', 'profesional'),
('Químico', 'quimico', 'profesional'),
('Geólogo', 'geologo', 'profesional'),
('Ingeniero Geólogo', 'ingeniero geologo', 'profesional'),
('Ingeniero Geógrafo', 'ingeniero geografo', 'profesional'),
('Ingeniero Hidrólogo', 'ingeniero hidrologo', 'profesional'),
('Ingeniero en Ciencias del Agua', 'ingeniero ciencias del agua', 'profesional'),
('Ingeniero Meteorólogo', 'ingeniero meteorologo', 'profesional'),
('Ingeniero Oceanográfico', 'ingeniero oceanografico', 'profesional'),
('Ingeniero en Geotecnia', 'ingeniero geotecnia', 'profesional'),
('Ingeniero en Tecnologías Geoespaciales', 'ingeniero tecnologias geoespaciales', 'profesional'),
('Ingeniero en Geociencias', 'ingeniero geociencias', 'profesional'),
('Ingeniero en Riesgos de Desastres', 'ingeniero riesgos desastres', 'profesional'),
('Físico', 'fisico', 'profesional'),
('Ingeniero Físico', 'ingeniero fisico', 'profesional'),
('Matemático', 'matematico', 'profesional'),
('Ingeniero Matemático', 'ingeniero matematico', 'profesional'),
('Ingeniero Estadístico', 'ingeniero estadistico', 'profesional'),
('Ingeniero en Logística y Transporte', 'ingeniero logistica transporte', 'profesional'),
('Ingeniero en Náutica y Operaciones Marítimas', 'ingeniero nutica operaciones maritimas', 'profesional'),
('Ingeniero en Computación', 'ingeniero computacion', 'profesional'),
('Ingeniero en Ciencias de la Computación', 'ingeniero ciencias computacion', 'profesional'),
('Ingeniero en Tecnologías de la Información', 'ingeniero tecnologias informacion', 'profesional'),
('Ingeniero de Software', 'ingeniero software', 'profesional'),
('Ingeniero en Sistemas de Información', 'ingeniero sistemas informacion', 'profesional'),
('Ingeniero de Polímeros', 'ingeniero polimeros', 'profesional'),
('Petroquímico', 'petroquimico', 'profesional'),
('Ingeniero Químico', 'ingeniero quimico', 'profesional'),
('Ingeniero Ambiental', 'ingeniero ambiental', 'profesional'),
('Ingeniero Eléctrico', 'ingeniero electrico', 'profesional'),
('Ingeniero en Electrónica', 'ingeniero electronica', 'profesional'),
('Ingeniero en Electrónica y Automatización', 'ingeniero electronica automatizacion', 'profesional'),
('Ingeniero Electromecánico', 'ingeniero electromecanico', 'profesional'),
('Ingeniero en Sonido y Acústica', 'ingeniero sonido acustica', 'profesional'),
('Ingeniero en Telemática', 'ingeniero telematica', 'profesional'),
('Ingeniero Mecánico', 'ingeniero mecanico', 'profesional'),
('Ingeniero en Metalurgia', 'ingeniero metalurgia', 'profesional'),
('Ingeniero Automotriz', 'ingeniero automotriz', 'profesional'),
('Ingeniero Naval', 'ingeniero naval', 'profesional'),
('Ingeniero Aeronáutico', 'ingeniero aeronautico', 'profesional'),
('Ingeniero Marítimo', 'ingeniero maritimo', 'profesional'),
('Ingeniero en Tecnologías Nucleares y Energéticas', 'ingeniero tecnologias nucleares energeticas', 'profesional'),
('Ingeniero en Mecatrónica', 'ingeniero mecatronica', 'profesional'),
('Ingeniero en Hidráulica', 'ingeniero hidraulica', 'profesional'),
('Ingeniero en Telecomunicaciones', 'ingeniero telecomunicaciones', 'profesional'),
('Ingeniero en Nanotecnología', 'ingeniero nanotecnologia', 'profesional'),
('Ingeniero Agroindustrial', 'ingeniero agroindustrial', 'profesional'),
('Ingeniero en Alimentos', 'ingeniero alimentos', 'profesional'),
('Ingeniero en Materiales', 'ingeniero materiales', 'profesional'),
('Ingeniero Textil', 'ingeniero textil', 'profesional'),
('Ingeniero en Minas', 'ingeniero minas', 'profesional'),
('Ingeniero en Petróleos', 'ingeniero petroleos', 'profesional'),
('Ingeniero de la Producción', 'ingeniero produccion', 'profesional'),
('Ingeniero en Seguridad Industrial', 'ingeniero seguridad industrial', 'profesional'),
('Ingeniero en Diseño Industrial', 'ingeniero diseno industrial', 'profesional'),
('Ingeniero Industrial', 'ingeniero industrial', 'profesional'),
('Ingeniero en Mantenimiento Industrial', 'ingeniero mantenimiento industrial', 'profesional'),
('Licenciado en Urbanismo', 'urbanismo', 'profesional'),
('Restaurador y Conservador de Bienes Culturales', 'restaurador conservador bienes culturales', 'profesional'),
('Ingeniero Civil', 'ingeniero civil', 'profesional'),
('Arquitecto', 'arquitecto', 'profesional'),
('Arquitecto sostenible', 'arquitecto sostenible', 'profesional'),
('Ingeniero Agrónomo', 'ingeniero agronomo', 'profesional'),
('Ingeniero Agropecuario', 'ingeniero agropecuario', 'profesional'),
('Ingeniero Agrícola', 'ingeniero agricola', 'profesional'),
('Ingeniero Zootecnista', 'ingeniero zootecnista', 'profesional'),
('Ingeniero Agrícola y Biológico', 'ingeniero agricola biologico', 'profesional'),
('Ingeniero en Agroecología', 'ingeniero agroecologia', 'profesional'),
('Ingeniero Forestal', 'ingeniero forestal', 'profesional'),
('Ingeniero Acuícola', 'ingeniero acuicola', 'profesional'),
('Médico Veterinario', 'medico veterinario', 'profesional'),
('Odontólogo', 'odontologo', 'profesional'),
('Médico General', 'medico general', 'profesional'),
('Licenciado en Enfermería', 'enfermeria', 'profesional'),
('Obstetriz', 'obstetriz', 'profesional'),
('Licenciado en Imagenología y Radiología', 'imagenologia radiologia', 'profesional'),
('Licenciado en Optometría', 'optometria', 'profesional'),
('Licenciado en Atención Prehospitalaria y Emergencias', 'atencion prehospitalaria emergencias', 'profesional'),
('Bioquímico Farmacéutico', 'bioquimico farmaceutico', 'profesional'),
('Licenciado en Laboratorio Clínico', 'laboratorio clinico', 'profesional'),
('Licenciado en Fisioterapia', 'fisioterapia', 'profesional'),
('Licenciado en Terapia Ocupacional', 'terapia ocupacional', 'profesional'),
('Licenciado en Fonoaudiología', 'fonoaudiologia', 'profesional'),
('Licenciado en Psicología Clínica', 'psicologia clinica', 'profesional'),
('Licenciado en Nutrición y Dietética', 'nutricion dietetica', 'profesional'),
('Licenciado en Terapia Respiratoria', 'terapia respiratoria', 'profesional'),
('Licenciado en Estimulación Temprana en Salud', 'estimulacion temprana salud', 'profesional'),
('Licenciado en Terapia Física', 'terapia fisica', 'profesional'),
('Licenciado en Farmacia', 'farmacia', 'profesional'),
('Licenciado en Promoción de la Salud', 'promocion salud', 'profesional'),
('Licenciado en Asistencia a Adultos Mayores', 'asistencia adultos mayores', 'profesional'),
('Licenciado en Hospitalidad y Hotelería', 'hospitalidad hoteleria', 'profesional'),
('Licenciado en Gastronomía', 'gastronomia', 'profesional'),
('Licenciado en Entrenamiento Deportivo', 'entrenamiento deportivo', 'profesional'),
('Licenciado en Gestión Deportiva', 'gestion deportiva', 'profesional'),
('Licenciado en Turismo', 'turismo', 'profesional'),
('Licenciado en Gestión de Riesgos y Desastres', 'gestion riesgos desastres', 'profesional'),
('Licenciado en Seguridad y Salud Ocupacional', 'seguridad salud ocupacional', 'profesional'),
('Licenciado en Gestión Ambiental', 'gestion ambiental', 'profesional'),
('Licenciado en Ciencias Militares', 'ciencias militares', 'profesional'),
('Oficial de Marina', 'oficial marina', 'profesional'),
('Licenciado en Ciencias Aeronáuticas Militares', 'ciencias aeronauticas militares', 'profesional'),
('Licenciado en Ciencias Policiales', 'ciencias policiales', 'profesional'),
('Licenciado en Ciencias Policiales y Seguridad Ciudadana', 'ciencias policiales seguridad ciudadana', 'profesional'),
('Licenciado en Seguridad Ciudadana', 'seguridad ciudadana', 'profesional'),
('Licenciado en Gestión del Transporte', 'gestion transporte', 'profesional'),
('Oficial de Marina Mercante', 'oficial marina mercante', 'profesional');

-- ================================================================
-- INSERT: Artesanos
-- ================================================================

INSERT INTO catalogue_profesiones (nombre, nombre_normalizado, tipo) VALUES
('Textiles y fibras', 'textiles fibras', 'artesanal'),
('Tejedor/a en telar', 'tejedor telar', 'artesanal'),
('Bordador/a', 'bordador', 'artesanal'),
('Tejedor/a de paja toquilla', 'tejedor paja toquilla', 'artesanal'),
('Hilandero/a de lana', 'hilandero lana', 'artesanal'),
('Tejedor/a de mochilas y canastos', 'tejedor mochilas canastos', 'artesanal'),
('Tejedor/a de alfombras y tapices', 'tejedor alfombras tapices', 'artesanal'),
('Tejedor/a de prendas tradicionales', 'tejedor prendas tradicionales', 'artesanal'),
('Alfarero/a', 'alfarero', 'artesanal'),
('Ceramista tradicional', 'ceramista tradicional', 'artesanal'),
('Modelador/a de masapán', 'modelador masapan', 'artesanal'),
('Artesano/a de cerámica amazónica', 'artesano ceramica amazonica', 'artesanal'),
('Ceramista moderno/a', 'ceramista moderno', 'artesanal'),
('Cester/a', 'cester', 'artesanal'),
('Artesano/a de tagua', 'artesano tagua', 'artesanal'),
('Artesano/a de palma y fibras silvestres', 'artesano palma fibras silvestres', 'artesanal'),
('Tallador/a de madera', 'tallador madera', 'artesanal'),
('Tornero/a de madera', 'tornero madera', 'artesanal'),
('Ebanista', 'ebanista', 'artesanal'),
('Artesano/a de juguetes de madera', 'artesano juguetes madera', 'artesanal'),
('Escultor/a en madera', 'escultor madera', 'artesanal'),
('Orfebre', 'orfebre', 'artesanal'),
('Platero/a', 'platero', 'artesanal'),
('Fundidor/a de metales', 'fundidor metales', 'artesanal'),
('Forjador/a', 'forjador', 'artesanal'),
('Curtidor/a de cuero', 'curtidor cuero', 'artesanal'),
('Zapater/a artesanal', 'zapater artesanal', 'artesanal'),
('Talabarter/a', 'talabarter', 'artesanal'),
('Confeccionista textil', 'confeccionista textil', 'artesanal'),
('Sastre/a artesanal', 'sastre artesanal', 'artesanal'),
('Artesano/a de sombreros de paja toquilla', 'artesano sombreros paja toquilla', 'artesanal'),
('Pintor/a artesanal', 'pintor artesanal', 'artesanal'),
('Decorador/a de cerámica', 'decorador ceramica', 'artesanal'),
('Grabador/a', 'grabador', 'artesanal'),
('Diseñador/a textil contemporáneo/a', 'diseñador textil contemporaneo', 'artesanal'),
('Ilustrador/a artesanal', 'ilustrador artesanal', 'artesanal'),
('Luthier', 'luthier', 'artesanal'),
('Artesano/a de flautas y zamponas', 'artesano flautas zamponas', 'artesanal'),
('Encadernador/a', 'encadernador', 'artesanal'),
('Cerero/a', 'cerero', 'artesanal'),
('Florero/a', 'florero', 'artesanal'),
('Acróbata de manualidades varias', 'acrobata manualidades varias', 'artesanal'),
('Hojalater/a artesanal', 'hojalatero artesanal', 'artesanal'),
('Reparador/a artesanal', 'reparador artesanal', 'artesanal');

-- ================================================================
-- Verificación
-- ================================================================

-- Conteo por tipo
SELECT tipo, COUNT(*) as total
FROM catalogue_profesiones
GROUP BY tipo
ORDER BY tipo;

-- Buscar duplicados en nombre_normalizado (debería estar vacío)
SELECT nombre_normalizado, COUNT(*)
FROM catalogue_profesiones
GROUP BY nombre_normalizado
HAVING COUNT(*) > 1;

-- Ejemplo de búsqueda normalizada
-- SELECT nombre, nombre_normalizado
-- FROM catalogue_profesiones
-- WHERE nombre_normalizado LIKE '%fisico%';
